repos:
  # Python code formatters
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        exclude: ^(backend/\.archive/|backend/frontend/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(backend/\.archive/|backend/frontend/)

  # Python linter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(backend/\.archive/|backend/frontend/)

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock\.json

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(backend/.*\.yml|.*fixtures.*\.yaml)
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: ^(backend/\.archive/|CHANGELOG\.md)

  # Frontend (TypeScript/JavaScript)
  - repo: local
    hooks:
      - id: frontend-lint
        name: Frontend ESLint
        entry: bash -c 'cd frontend && npm run lint:fix || true'
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false

# Configuration
default_language_version:
  python: python3.11

exclude: |
  (?x)^(
    backend/\.archive/.*|
    backend/frontend/.*|
    backend/migrations/.*|
    .*\.min\.js|
    .*\.min\.css|
    node_modules/.*|
    \.venv/.*|
    \.env.*|
    backend/test_.*\.py|
    backend/fix_.*\.py
  )$