global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'genesis-monitor'
    environment: 'development'

scrape_configs:
  # GENESIS FastAPI Application
  - job_name: 'genesis-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if running)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']

# Alerting rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Alert manager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []