name: ADK Compatibility Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/agents/**'
      - 'backend/adk/**'
      - 'backend/tests/**'
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  adk-compatibility:
    name: ADK Compatibility Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        poetry install --with dev
    
    - name: Verify ADK structure
      working-directory: ./backend
      run: |
        echo "🔍 Verificando estructura ADK..."
        
        # Verificar que todos los agentes hereden de BaseNGXAgent y ADKAgent
        for agent in agents/*/agent.py; do
          if [ -f "$agent" ]; then
            echo "Checking $agent..."
            grep -q "class.*BaseNGXAgent.*ADKAgent" "$agent" || echo "⚠️ $agent no hereda correctamente"
          fi
        done
    
    - name: Run ADK tests
      working-directory: ./backend
      run: |
        poetry run pytest tests/test_adapters -v --tb=short -k "adk or ADK"
    
    - name: Test agent imports
      working-directory: ./backend
      run: |
        poetry run python -c "
        print('Testing agent imports...')
        try:
            from agents.orchestrator.agent import NGXNexusOrchestrator
            print('✅ Orchestrator import OK')
        except Exception as e:
            print(f'❌ Orchestrator import failed: {e}')
            
        try:
            from agents.elite_training_strategist.agent import NGXBlazeEliteTrainingStrategist
            print('✅ Elite Training import OK')
        except Exception as e:
            print(f'❌ Elite Training import failed: {e}')
            
        try:
            from agents.precision_nutrition_architect.agent import NGXSagePrecisionNutritionArchitect
            print('✅ Nutrition import OK')
        except Exception as e:
            print(f'❌ Nutrition import failed: {e}')
        "